"""Primitives DSL and interpreter."""

from .dsl import (
    PrimitiveType,
    Primitive,
    Program,
    Selection,
    SelectParams,
    TransformParams,
    PaintParams,
    FilterParams,
    CompositeParams,
    CopyParams,
    ExtractParams,
    GravityParams,
    SelectCriteria,
    TransformAction,
    PaintAction,
    FilterCondition,
    CompositeMode,
    # Convenience constructors
    select,
    transform,
    paint,
    filter_sel,
    composite,
    copy,
    extract,
    gravity,
)
from .interpreter import PrimitiveInterpreter, ExecutionState

__all__ = [
    "PrimitiveType",
    "Primitive",
    "Program",
    "Selection",
    "SelectParams",
    "TransformParams",
    "PaintParams",
    "FilterParams",
    "CompositeParams",
    "CopyParams",
    "ExtractParams",
    "GravityParams",
    "SelectCriteria",
    "TransformAction",
    "PaintAction",
    "FilterCondition",
    "CompositeMode",
    "PrimitiveInterpreter",
    "ExecutionState",
    # Convenience constructors
    "select",
    "transform",
    "paint",
    "filter_sel",
    "composite",
    "copy",
    "extract",
    "gravity",
]
